### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by nevillelyh** [spotify/beam#11]
Right now we have a lot of names that are confusing. Should we consolidate them?

My rough ideas:

Both read/write:
- Bucket - a subset of data of a single data set after hashing
- `BucketMetadata` - metadata for a single data set in SortedBucket format
- `FileOperation` - rename from `SortedBucketFile` since that one is confusing with other `SortedBucket*`
- `KeyT` - user defined key type of a data set, can be shortened to `K` in inner classes, rename `SortingKeyT` to `KeyT`
- `ValueT` - user defined value type of a data set, `V` for short in inner classes
 
Read:
- `BucketGroup` - the same hashed subset of data across multiple data sets in a join/cogroup
- rename `KeyT` and `ResultT` in `SortedBucketSource` to something like `MergedKey`, `MergedValue`, and `SMBCoGbkResult#ToResult` to `Merge`?

Other thoughts:
- `SortedBucketSource`, `KeyedBucketSources`, `KeyedBucketSource` - these names are a bit confusing. We should probably keep the first to be consistent with Beam and the sink. Rename the 2nd to `BucketInput` (since it extends `PInput`) and the 3rd to `SortedBucketDataset` (since it's user facing)?

**Comment by clairemcginty** [comment]
I like these! Mostly agree, with a few thoughts:

- Maybe `FileOperations`, not `FileOperation`? Since it covers reads and writes.
- I don't think `Merge` is the quite right verb to use in `SortedBucketSource` . how about `FinalKeyT`/`FinalResultT`/`ToFinalResult` ?
- Just semantically I think `BucketInput` is kind of vague, it seems like it would represent a single bucket. For example, in `CoGroupByKey` they call their `PInput` implementation `KeyedPCollectionTuple`. Maybe we could call ours `BucketedPCollectionTuple` ?

**Comment by clairemcginty** [comment]
on second thought, `BucketedPCollectionTuple` isn't appropriate either since it's not actually a `PCollection` at that point, just an un-opened file reader. `BucketedInput`/`BucketedInputSource`/`BucketedCollection` ?

**Comment by nevillelyh** [comment]
Let's just go with `BucketedInput` the shortest and change if we come up with a better one later?
