### ISSUE TITLE
Implement bucket/sort PTransform

### ISSUE THREAD

**Issue by clairemcginty** [spotify/beam#4]
Belongs to #1 

Assuming the SMB sink (#2) requires input that's already in sorted bucket format, we should create a custom `PTransform` to apply the grouping and sorting to a `PCollection` of elements.

Open questions:
- How much customization should should the user be able to specify? I.e. can they set desired # of buckets as well as a custom bucketing function? What happens if their dataset has an especially hot key and its values can't fit in memory? Or if it just linearly grows enough to outgrow the original # of buckets?

**Comment by clairemcginty** [comment]
We can do all of this in the sink itself instead of adding an extra `PTransform`... probably much simpler for the user that way.

**Comment by Illedran** [comment]
Beam has a sorting module available (https://beam.apache.org/documentation/sdks/java-extensions/).
However, it sorts by byte representation and is a bit expensive since it's serializing back and forth.

Since we're going to write out the data anyway, you can serialize the data before the grouping/sorting operation. `SortValues` can be modified to not encode/decode data to bytes, and the sink can then simply write out those bytes. 

I have an example of this here (shuffling): https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/SMBShuffle.java
Write out: https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/SMBAvroSink.java#L77

**Comment by Illedran** [comment]
Expanding on the open questions: 
Hot *bucket* keys can arise even if there are no hot *input* keys, this is called partitioning skew in the MapReduce world. 

Consider the output from hashing the keys is `H = {0, 1, 2, 3, 4, 5, 8, 11, 14, 17}` modulo 3 buckets (the keys are different as they hash to different values). The buckets will be `b0 = {0, 3}, b1 = {1, 4}, b2 = {2, 5, 8, 11, 14, 17}`. b2 may not fit in memory even if the input data has no hot keys.

**Comment by clairemcginty** [comment]
thanks for the comments @Illedran! I think I'm going to break this up into 2 separate tickets so each discussion can be more focused
