### ISSUE TITLE
Implement bucketing

### ISSUE THREAD

**Issue by clairemcginty** [spotify/beam#9]
belongs to #1
forked off of #4 

basic idea is to offer a few sane hashing algorithms (i.e. mumur3) as default options for a user to choose, then let them choose desired number of buckets. the hashing algorithm should have some serialized representation in the written metadata file.

per @Illedran:

> Expanding on the open questions:
> Hot _bucket_ keys can arise even if there are no hot _input_ keys, this is called partitioning skew in the MapReduce world.
> 
> Consider the output from hashing the keys is `H = {0, 1, 2, 3, 4, 5, 8, 11, 14, 17}` modulo 3 buckets (the keys are different as they hash to different values). The buckets will be `b0 = {0, 3}, b1 = {1, 4}, b2 = {2, 5, 8, 11, 14, 17}`. b2 may not fit in memory even if the input data has no hot keys.

**Comment by clairemcginty** [comment]
other bucketing issues that may be outside the scope of this ticket...

- Sharding per-bucket if the contents of a bucket can't fit in one file.
- Output filename convention. at least internally, a lot of our user code assumes file names will follow the pattern `part-%d-of-%d.$SUFFIX`. Using a filename like `bucket-%d-shard-%d-of-%d.$SUFFIX` might be a breaking change if our existing batch pipelines migrate over to SMB sink.

**Comment by nevillelyh** [comment]
We can make the `part/shard` prefix configurable? `part-*` convention is only enforced by Scio & our internal code.

**Comment by clairemcginty** [comment]
yeah I mean the prefix string is absolutely configurable, it's just that the `part-*` syntax Scio uses only expects two numbers to represent shard position--so we couldn't encoding per-bucket-sharding info into the filename itself, we'd need some kind of file manifest in the metadata to reconstruct that information.

**Comment by clairemcginty** [comment]
Thinking more about bucket sharding... I can see a few ways of doing this:

- Ask the user to specify # of shards per bucket statically. If they know their dataset well enough, could probably pick a reasonable number of buckets, but this could be problematic if it grows unexpectedly or the buckets greatly vary in size.

- Ask the user to specify either target number of records per bucket shard. It's easy enough to do a count by key once bucket has been assigned so each bucket could have a dynamic # of shards. it could be exposed in the sink api as something like `PTransform<PCollection<KV<Integer, KV<SortingKeyT, ValueT>>>, PCollectionView<Map<Integer, Integer>>> shardingProvider` where the `PCollectionView<Map<Integer, Integer>>` is a map of bucket -> number shards. @illedran it looks like [your implementation ](https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/ResolveSkewness.java)is doing more or less this by using a heuristic function with a user-supplied constant?

- Ask the user to specify target byte size per bucket shard, then we could just keep track of bytes written to the `WritableByteChannel` and close/open a new Writer every time we reach the limit of bytes. this seems mostly simple although we don't know up front what the total # of shards is, so we'd have to do another pass to get the file name in `shard-%d-of-%d` format.

- No sharding, just trust the user has supplied a good enough # buckets/hash fn to not need them... but if they end up with an unexpected hot key their pipeline would just break until they increase bucket size.



With any of these implementations it seems like we'll have to write the shard files serially, since GBK returns a possibly lazy `Iterable` we don't really know the end of the list, or have a way to split the list into n shards up-front. Maybe if we do something fancy pre-grouping to include shard as part of the key but.... not sure. wdyt?

**Comment by Illedran** [comment]
@ClaireMcGinty The dynamic sharding I implemented creates shards that are within (1 + ε) times the average number of records in a shard (whereas the average is computed globally across all shards of all buckets), with ε as user input. This is my approach, but any other function with the same idea that uses some aggregate property of the data can be used.
The GBK then works on a tupled key of (bucketKey, shardKey) instead of just bucketKey, with the shardKey being assigned randomly or in round robin. It is important to assign the shardKey before the GBK else we might run into stragglers due to skewed buckets.

Alternatively, the other approach is assigning a target byte size per bucket: instead of counting the records per bucket, we can simply keep track of the size of the records in each bucket and compute the appropriate number of shards that can fit the data in the bucket.

By setting the size of each bucket we can also determine the number of buckets at runtime, which I do [here](https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/SMBAutoShuffle.java#L108) by dividing the total serialized size by the capacity of one bucket and rounding to the closest power of two. This is basically free to compute as I'm serializing the data anyway before the SortValues. This also makes it so that we don't create too many buckets or too few (and SMB join works within factors of 2).

**Comment by clairemcginty** [comment]
Thanks, @Illedran! If I'm understanding correctly, the first idea with the tupled (bucketKey, shardKey), where shardKey is randomly assigned, only maintains sorted order within each bucket shard--we couldn't just read a bucket's sharded files in sequentially and know every key in shard 1 < every key in shard2, etc. is that right? How does this get resolved at join time? do all sources have to use the same sharding key assignment?

I kind of like the idea of using target byte size per bucket shard, since we can maintain a total ordering over the whole bucket, although this means we can't write/read from shards in parallel--which, if the user chooses a good # of buckets/shard size, doesn't have to be a disadvantage. I think it would make the read/join operation more straightforward since it's just a simple sequential read across all files matching the `/bucket-M-of-N-shard-*` file pattern. @nevillelyh wdyt?

**Comment by Illedran** [comment]
There is no total ordering across all the shards of a bucket. One way to make joining work is computing the join between all pairs of shards between left and right side. So a join between a buckets with 3 shards and one with 5 would result in computing the join over 15 pairs of (left, right) shards. Some other considerations:
1. Each "join pair of shards" task is independent and the shards of a bucket may be processed by multiple workers in parallel. I guess there could be optimizations for data locality, even though Dataflow does not have such optimizations afaik (?). In other words with no total ordering on the shards, we can read/write shards in parallel.
2. Since we are joining multiple shards in parallel, there are some interesting semantics with the results. Assuming the output type of the SMBRead operation is `PCollection<KV<K, KV<Iterable<L>, Iterable<R>>>>`, we might have multiple items with the same key K in the PCollection, which might/might not be a problem. 
3. Computing the merge-join over all pairs of shards makes it so that each shard is read a \<number of shards in the other bucket\> times **sequentially**. Intuitively, this is kind of like replicating the data inside each shard: if one side only has one shard, this is equivalent to a map-side join in the MapReduce sense. How to implement join types beyond inner equijoin in this case?

Regarding the sharding key, maybe there is a way to assign one deterministically?

@ClaireMcGinty The only concern with having total ordering in a bucket means that we need to GBK on the bucket key which might be skewed (because of the data itself or for partitioning skew).
